language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: lS1r3ot13mlIz18hn9VbjYeZVl8peV6hgcm5HW0B9wTSU8qL/uVKg91m5Vk/ss1X/vckqumNpSRnBX76pA7THG6wuB01jYlHMbINVhg00nrubScwggqFwFhjhX2Uiv23gXEIFNU04A0RfAnYCRRR+h/Y72ewE3j/XO35SAmMXM4MxAAtqBEDRfstkIiT3bTj67ZLt+Oz8vyl8lYB/wHSwEY5CLtFKThFESyjEAYu4hA2wfAmNCiwtiv427i7ylDpdLcrPXitYTuZvDGuBT96hdXj+rGd52cGMf8VGG8+7xG1eKEhMQUwq44sceJ2lFwZnpNwRD1lICnRLjUGDTbr+OIHreS/6o4P+8Uvz5jAKHsV6RSET8UQDszyVUAIh9I29kd61a4OmLXrhskK/RWLzU8Keb4vb94EchkV1ZH+l8ekN9QbWpzabgSqU4o7uvPJTZIrP8eVd7Z3+0yjPy9gHR9gClWzBY8XCSP+OiU9UmdFIRr7ljcHtcY96XSeWidGLkBhhH9dOlCVZOkoWYXJ99n3HIFq89ypoln5DBjQ1PPzBihbULsT8Kropn4dfmWPokJZb87ovyQ99KcdUkOQQk+NWh3lGcWxcwCfS2fOK77vnh7n57bDvVCLAP+Y5E2gcY1i8ORhitJYWQ3rS6CZbafLnISa+7pfTksj3CEn+Zc=
